if(NOT DEFINED TILEXR_COLLECTIVES_OP)
    message(FATAL_ERROR "TILEXR_COLLECTIVES_OP is required")
endif()
if(NOT DEFINED TILEXR_COLLECTIVES_KERNEL_EMBED_CPP)
    message(FATAL_ERROR "TILEXR_COLLECTIVES_KERNEL_EMBED_CPP is required")
endif()
if(NOT EXISTS "${TILEXR_COLLECTIVES_OP}")
    message(FATAL_ERROR "Collectives CCE object not found: ${TILEXR_COLLECTIVES_OP}")
endif()

file(SIZE "${TILEXR_COLLECTIVES_OP}" _tilexr_collectives_size)

file(WRITE "${TILEXR_COLLECTIVES_KERNEL_EMBED_CPP}" "/*
 * Generated by src/collectives/cmake/embed_collectives_kernel.cmake.
 */
#include <cstddef>
#include <cstdint>

extern \"C\" {
extern const std::size_t TileXRCollectivesKernelBinarySize = ${_tilexr_collectives_size};
}

asm(R\"(
.section .rodata, \"a\", @progbits
.balign 16
.global TileXRCollectivesKernelBinaryData
.type TileXRCollectivesKernelBinaryData, @object
TileXRCollectivesKernelBinaryData:
.incbin \"${TILEXR_COLLECTIVES_OP}\"
TileXRCollectivesKernelBinaryDataEnd:
.size TileXRCollectivesKernelBinaryData, TileXRCollectivesKernelBinaryDataEnd - TileXRCollectivesKernelBinaryData
.previous
)\");
")
